hidroh/materialistic

README.md

Changed Dagger's url from https://https://github.com/square/dagger to https://github.com/square/dagger

Changed Dagger url.

---

README.md
app/build.gradle
app/src/main/res/values/styles.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityLandTest.java
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityTest.java

Upgrade to support library v22.1.0

---

app/src/main/java/io/github/hidroh/materialistic/AskActivity.java
app/src/main/java/io/github/hidroh/materialistic/BaseStoriesActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/JobsActivity.java
app/src/main/java/io/github/hidroh/materialistic/ListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/NewActivity.java
app/src/main/java/io/github/hidroh/materialistic/SearchActivity.java
app/src/main/java/io/github/hidroh/materialistic/ShowActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderEdgeTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/StoriesActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/WebActivityLocalTest.java
app/src/test/java/io/github/hidroh/materialistic/WebActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsItemTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java
app/src/test/java/io/github/hidroh/materialistic/test/TestWebItem.java

Switch enum to StringDef

---

app/src/main/res/values/strings.xml

Added whitespace between full stop and start of new sentence.

Fix grammatical error

---

app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebActivity.java
app/src/main/res/menu-w820dp-land/menu_list_land.xml
app/src/main/res/menu/menu_share.xml
app/src/main/res/menu/menu_web.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
jacoco.gradle

Make share options more prominent

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/WebActivity.java
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/WebActivityTest.java

Convert toasts to snackbars

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java

Use Chrome custom tabs

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/MultiPaneListener.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/MultiPageItemRecyclerViewAdapter.java
app/src/main/res/layout/fragment_web_hn.xml
app/src/main/res/layout/item_header.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityLandTest.java
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ListActivity.java

Remove shared element transition

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/MultiPageItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/SinglePageItemRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsItemTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java
app/src/test/java/io/github/hidroh/materialistic/test/TestWebItem.java

Abbreviate time in list

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/Scrollable.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/res/layout/fragment_web.xml
app/src/main/res/layout/fragment_web_hn.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowNestedScrollView.java

Allow scroll to top action

---

app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/res/layout/button_download.xml
app/src/main/res/layout/fragment_web.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java

Replace download dialog with button

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java

Fix external browser options

---

app/src/main/res/layout/item_comment.xml

Make text selectable

---

app/src/main/java/io/github/hidroh/materialistic/data/FeedbackClient.java

Add device and app information to feedback

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/SearchActivity.java

Fix issues with refresh and search query

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/AsteriskSpan.java
app/src/main/res/layout/fragment_list.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsItemTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java

Highlight new stories

---

app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java

Add HN item URL to email export

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/TrackableActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/AsteriskSpan.java
app/src/main/res/layout/activity_item.xml
app/src/main/res/layout/activity_list.xml
app/src/main/res/layout/fragment_readability.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/PreferencesTextSizeTest.java
app/src/test/java/io/github/hidroh/materialistic/PreferencesThemeTest.java

Allow more than 2 themes

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/LazyLoadFragment.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentLazyLoadTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentLocalTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java

Lazy load non visible content for non-wifi connections

---

app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/MultiPageItemRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java

Override default view when open comments

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/res/layout/fragment_readability.xml
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java

Use link movement method for text view links

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/MaterialisticProvider.java
app/src/main/java/io/github/hidroh/materialistic/data/ReadabilityClient.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentLazyLoadTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ReadabilityClientTest.java

Cache fetched readability articles

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java

Fix text selection crash on Marshmallow

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryView.java
app/src/main/res/layout/item_favorite.xml
app/src/main/res/layout/item_story.xml
app/src/main/res/layout/local_story_view.xml
app/src/main/res/layout/story_view.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/styles.xml

Initial version of story view

---

app/src/main/java/io/github/hidroh/materialistic/LazyLoadFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/preference/HelpLazyLoadView.java
app/src/main/java/io/github/hidroh/materialistic/widget/preference/HelpListView.java
app/src/main/res/layout/help_lazy_load.xml
app/src/main/res/layout/include_help_lazy_load.xml
app/src/main/res/layout/include_help_list_view.xml
app/src/main/res/layout/preference_help.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentLazyLoadTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/SettingsActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentLocalTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java

resolves #211, also mentioned in #159

Add option to toggle lazy loading

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java

Add missing title when sharing thru Chrome tab

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/DrawerFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/LoginActivity.java
app/src/main/java/io/github/hidroh/materialistic/accounts/AccountAuthenticator.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServices.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java
app/src/main/java/io/github/hidroh/materialistic/widget/PopupMenu.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/menu/menu_contextual_story.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/LoginActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java
app/src/test/java/io/github/hidroh/materialistic/accounts/AccountAuthenticatorTest.java
app/src/test/java/io/github/hidroh/materialistic/accounts/UserServicesClientTest.java
jacoco.gradle

Add vote option to list item overflow menu

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/DrawerFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/res/layout/item_header.xml
app/src/main/res/layout/story_view.xml
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java

Add vote button to item view

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryView.java
app/src/main/res/layout/button_more.xml
app/src/main/res/layout/item_comment.xml
app/src/main/res/layout/story_view.xml
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java

Add more options button to story list items

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java

Make pending intent one time only

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/LoginActivity.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServices.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/LoginActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/accounts/UserServicesClientTest.java

Allow account creation via login

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/res/layout/activity_item.xml
app/src/main/res/layout/activity_list.xml
app/src/main/res/layout/button_reply.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityLandTest.java

Add reply FAB for landscape

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/res/layout/item_comment.xml
app/src/main/res/layout/local_story_view.xml
app/src/main/res/values/strings.xml

Highlight logged in user posts

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ScrollAwareFABBehavior.java
app/src/main/res/layout/button_reply.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityLandTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowFloatingActionButton.java

Show/hide FAB instead of add/remove from parent

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/MultiPageItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/SinglePageItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryView.java
app/src/main/java/io/github/hidroh/materialistic/widget/ToggleItemViewHolder.java
app/src/main/res/layout/item_comment.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java

Add links to user profiles

---

app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/UserManager.java
app/src/main/res/layout/activity_user.xml
app/src/main/res/layout/empty_item.xml
app/src/main/res/layout/fragment_item.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/UserItemTest.java

Handle missing user info

---

app/src/main/java/io/github/hidroh/materialistic/widget/SubmissionRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java

Display score for stories

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/res/layout/activity_list.xml

Restore selected item on landscape

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/ThreadPreviewActivity.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/SubmissionRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/SubmissionViewHolder.java
app/src/main/java/io/github/hidroh/materialistic/widget/ThreadPreviewRecyclerViewAdapter.java
app/src/main/res/layout/activity_thread_preview.xml
app/src/main/res/layout/item_submission.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java
app/src/test/java/io/github/hidroh/materialistic/ThreadPreviewActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java

Preview user comment thread

---

app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/res/menu/menu_contextual_story.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java

Add link to user from story list

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/data/SessionManager.java
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsItemTest.java
app/src/test/java/io/github/hidroh/materialistic/data/SessionManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java

Replace broadcast with content observer

---

app/src/main/res/values/license.xml
app/src/main/res/values/non_translatable.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml

Split non translatable string resources

---

CONTRIBUTING.md
README.md

Add contributing notes

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java

Avoid hard reference to context from network callbacks

---

app/src/main/java/io/github/hidroh/materialistic/DrawerActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/MultiPageItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/SubmissionRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ThreadPreviewActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowRecyclerViewAdapter.java

Replace anonymous callbacks with static nested ones

---

app/src/main/java/io/github/hidroh/materialistic/BaseFragment.java
app/src/main/java/io/github/hidroh/materialistic/DrawerActivity.java
app/src/main/java/io/github/hidroh/materialistic/InjectableActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java

Check for attached status on callbacks

---

app/src/main/java/io/github/hidroh/materialistic/BaseFragment.java
app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java

Prevent options menu callbacks on detached

---

app/src/main/java/io/github/hidroh/materialistic/InjectableActivity.java

Avoid fragment transaction after state saved

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java

Persist external browser preference when saving state

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityTest.java

Only show chooser for HN links

---

app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/res/drawable/progress.xml
app/src/main/res/layout/fragment_readability.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Update progress color to improve contrast

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryView.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java
app/src/test/java/io/github/hidroh/materialistic/test/TestWebItem.java

Improve items lookup

---

app/build.gradle

Upgrade LeakCanary

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaClient.java
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaPopularClient.java
app/src/main/java/io/github/hidroh/materialistic/data/FeedbackClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ReadabilityClient.java
app/src/main/java/io/github/hidroh/materialistic/data/RestServiceFactory.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaPopularClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FeedbackClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ReadabilityClientTest.java

Upgrade to Retrofit2-beta3

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java
app/src/main/java/io/github/hidroh/materialistic/data/RestServiceFactory.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java
app/src/test/java/io/github/hidroh/materialistic/accounts/UserServicesClientTest.java

Upgrade OkHttp to 3.0.0-RC1

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java

Set cookie policy to accept original server

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java
app/src/test/java/io/github/hidroh/materialistic/accounts/UserServicesClientTest.java

Upgrade to OkHttp3

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaClient.java
app/src/main/java/io/github/hidroh/materialistic/data/FeedbackClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ReadabilityClient.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FeedbackClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ReadabilityClientTest.java
build.gradle

Upgrade Retrofit to latest SNAPSHOT for OkHttp3

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/arrays.xml

All of theme,I did not translate, because the literal translation is more blunt.

Support simplified Chinese

---

app/src/main/res/values-zh-rCN/strings.xml

Fix some irrational translation to meet the Chinese mainland's habits.

Update strings.xml of zh-rCN

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/widget/TintableTextView.java
app/src/main/res/layout/fragment_drawer.xml
app/src/main/res/values/attrs.xml
build.gradle

Use custom attr to specify tint drawables for TextView

---

app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ThemedActivity.java
app/src/main/res/values/styles.xml
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/PreferencesTextSizeTest.java
app/src/test/java/io/github/hidroh/materialistic/preference/FontSizePreferenceTest.java

Fix text size preference not applied

---

.travis.yml
app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/preference/ThemePreference.java
app/src/main/res/layout/preference_theme.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

Add new black theme, adjust dark theme

---

app/src/main/res/layout/activity_compose.xml
app/src/main/res/layout/activity_submit.xml

Capitalize input sentences

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseStoriesActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/UserItem.java
app/src/main/res/layout/empty_favorite.xml
app/src/main/res/layout/empty_item.xml
app/src/main/res/layout/empty_list.xml
app/src/main/res/layout/empty_readability.xml
app/src/main/res/layout/empty_search.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java

Cache API requests for offline access

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/NewActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderEdgeTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/ThreadPreviewActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentLocalTest.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java

Cache items for 1h, clear on forced refresh

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/AlgoliaClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemManager.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderEdgeTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/PopularActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/SearchActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaPopularClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/HackerNewsClientTest.java

Cache stories for 1h, clear on forced refresh

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/Application.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/accounts/AccountAuthenticator.java
app/src/main/java/io/github/hidroh/materialistic/accounts/EmptyAccountAuthenticator.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncAdapter.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncService.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncWifiReceiver.java
app/src/main/java/io/github/hidroh/materialistic/data/MaterialisticProvider.java
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/main/res/xml/syncadapter.xml
app/src/main/res/xml/syncauthenticator.xml
app/src/test/java/io/github/hidroh/materialistic/LoginActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ItemSyncAdapterTest.java
jacoco.gradle

Auto download saved items on wifi

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncAdapter.java
app/src/main/java/io/github/hidroh/materialistic/data/ReadabilityClient.java
app/src/main/java/io/github/hidroh/materialistic/data/RestServiceFactory.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentLazyLoadTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ItemSyncAdapterTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ReadabilityClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/TestRestServiceFactory.java

Sync readability together with saved item

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/OfflineWebActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncAdapter.java
app/src/main/res/layout/activity_offline_web.xml
app/src/main/res/layout/fragment_web.xml
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/OfflineWebActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowWebView.java

Cache web view content

---

app/src/main/java/io/github/hidroh/materialistic/OfflineWebActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/res/layout/activity_offline_web.xml
app/src/test/java/io/github/hidroh/materialistic/OfflineWebActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowWebView.java

Load web view from cache first, retry from network on error

---

app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java

Fix cache reload for redirections

---

app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncAdapter.java
app/src/main/java/io/github/hidroh/materialistic/preference/OfflineDataPreference.java
app/src/main/res/layout/preference_theme.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ItemSyncAdapterTest.java
app/src/test/java/io/github/hidroh/materialistic/preference/FontPreferenceTest.java
app/src/test/java/io/github/hidroh/materialistic/preference/FontSizePreferenceTest.java
app/src/test/java/io/github/hidroh/materialistic/preference/ThemePreferenceTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowSupportPreferenceManager.java

Add preferences to control offline sync

---

app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncAdapter.java
app/src/main/java/io/github/hidroh/materialistic/data/RestServiceFactory.java
app/src/test/java/io/github/hidroh/materialistic/data/TestRestServiceFactory.java

Execute retrofit callback on background thread

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/CustomTabsDelegate.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/CustomTabsDelegateTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java

Use sessions for Chrome custom tabs

---

app/src/main/res/layout/activity_compose.xml

Allow multiline input

---

app/src/main/res/layout/fragment_web.xml

Make WebView visible by default

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/LauncherActivity.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/preference/SimpleSpinnerPreference.java
app/src/main/res/values/arrays.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/io/github/hidroh/materialistic/LauncherActivityTest.java

Add option for default screen

---

app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/data/Favorite.java
app/src/main/java/io/github/hidroh/materialistic/data/Item.java
app/src/main/java/io/github/hidroh/materialistic/data/WebItem.java
app/src/main/res/layout/fragment_drawer.xml
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestWebItem.java

Do not reload saved items

---

.travis.yml
app/build.gradle
app/proguard-rules.pro
app/proguard-square.pro
app/proguard-support.pro

Enable proguard

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/DrawerFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/ReleaseNotesActivity.java
app/src/main/res/anim/slide_in_up.xml
app/src/main/res/anim/slide_out_down.xml
app/src/main/res/layout/activity_release.xml
app/src/main/res/layout/fragment_drawer.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/non_translatable.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/DrawerFragmentTest.java
app/src/test/java/io/github/hidroh/materialistic/ReleaseNotesActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java

Add release notes

---

app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsItem.java
app/src/main/java/io/github/hidroh/materialistic/data/SessionManager.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderEdgeTest.java
app/src/test/java/io/github/hidroh/materialistic/data/TestHnItem.java

Do not reload items being loaded

---

app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncAdapter.java
app/src/main/java/io/github/hidroh/materialistic/data/ItemSyncService.java
app/src/main/java/io/github/hidroh/materialistic/data/ResponseListener.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ItemSyncAdapterTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowWebView.java

Defer and sync deferred article and readability

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ThemedActivity.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/data/ReadabilityClient.java
app/src/main/java/io/github/hidroh/materialistic/data/RestServiceFactory.java
app/src/main/java/io/github/hidroh/materialistic/preference/ThemePreference.java
app/src/main/res/layout/activity_user.xml
app/src/main/res/layout/preference_theme.xml
app/src/main/res/layout/user_header.xml
app/src/main/res/values/themes.xml
app/src/test/java/io/github/hidroh/materialistic/PreferencesThemeTest.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/AlgoliaClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ReadabilityClientTest.java
app/src/test/java/io/github/hidroh/materialistic/preference/ThemePreferenceTest.java

Use bottom sheet for user profile

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/PopupSettingsFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/res/drawable/ic_format_line_spacing_white_24dp.xml
app/src/main/res/layout/fragment_popup_settings.xml
app/src/main/res/menu/menu_font_options.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_comments.xml
app/src/main/res/xml/preferences_readability.xml
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentMultiPageTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentTest.java

Use preference bottom sheet for view options

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/PopupSettingsFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/SinglePageItemRecyclerViewAdapter.java
app/src/main/res/values/arrays.xml
app/src/main/res/values/non_translatable.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/preferences_comments.xml
app/src/main/res/xml/preferences_readability.xml

Add line height option

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/CommentItemDecoration.java
app/src/main/res/values/arrays.xml
app/src/main/res/values/colors.xml
jacoco.gradle

Add level decoration, adjust colors

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/Findable.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ReadabilityFragment.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java
app/src/main/res/drawable/ic_clear_white_24dp.xml
app/src/main/res/drawable/ic_search_white_24dp.xml
app/src/main/res/layout/dialog_find.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/test/java/io/github/hidroh/materialistic/test/ShadowWebView.java
app/src/test/java/io/github/hidroh/materialistic/widget/ItemPagerAdapterTest.java
lint.xml

Add simple find in page

---

app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/FeedbackActivity.java
app/src/main/java/io/github/hidroh/materialistic/ReleaseNotesActivity.java
app/src/main/java/io/github/hidroh/materialistic/ThemedActivity.java
app/src/main/java/io/github/hidroh/materialistic/ThreadPreviewActivity.java
app/src/main/res/layout/user_header.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Set window background dynamically

---

app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java

Update vote params

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/ComposeActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/LoginActivity.java
app/src/main/java/io/github/hidroh/materialistic/SubmitActivity.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServices.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ComposeActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/LoginActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/SubmitActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/accounts/UserServicesClientTest.java

Redirect to submitted item if duplicate

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/BaseWebFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/KeyDelegate.java
app/src/main/java/io/github/hidroh/materialistic/ThreadPreviewActivity.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityLandTest.java
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/KeyDelegateTest.java
app/src/test/java/io/github/hidroh/materialistic/NestedScrollViewScrollHelperTest.java
app/src/test/java/io/github/hidroh/materialistic/RecyclerViewScrollHelperTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java
app/src/test/java/io/github/hidroh/materialistic/ThreadPreviewActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/UserActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/WebFragmentTest.java

Back press to handle WebView go back

---

app/src/main/java/io/github/hidroh/materialistic/ActivityModule.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java

Only use cookies for chained submit request

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java

Include both title and URL when sharing

---

app/src/main/java/io/github/hidroh/materialistic/SubmitActivity.java
app/src/test/java/io/github/hidroh/materialistic/SubmitActivityTest.java

related to #559, but the other way around

Derive share title from URL or simple text

---

app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsItem.java
app/src/main/java/io/github/hidroh/materialistic/data/Item.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryView.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java
app/src/test/java/javax/microedition/khronos/opengles/GL.java

Allow list item swipe actions

---

app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_list.xml
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowLinearLayoutManager.java
app/src/test/java/io/github/hidroh/materialistic/test/ShadowRecyclerView.java

Add option to auto mark as viewed

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/res/layout/activity_offline_web.xml
app/src/main/res/layout/fragment_web.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/main/res/xml/preferences_list.xml

Fix incorrect cache mode, overlapping toolbar

---

app/build.gradle

Target API 23 due to AOSP bug

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseWebFragment.java
app/src/main/java/io/github/hidroh/materialistic/OfflineWebActivity.java

Disable pinch zoom when not in fullscreen

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/KeyDelegate.java
app/src/main/java/io/github/hidroh/materialistic/Navigable.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsItem.java
app/src/main/java/io/github/hidroh/materialistic/data/Item.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/NavFloatingActionButton.java
app/src/main/java/io/github/hidroh/materialistic/widget/SinglePageItemRecyclerViewAdapter.java
app/src/main/res/drawable/ic_gamepad_white_24dp.xml
app/src/main/res/layout-w820dp-land/activity_list.xml
app/src/main/res/layout/activity_item.xml
app/src/main/res/layout/button_navigation.xml
app/src/main/res/layout/dialog_konami.xml
app/src/main/res/layout/help_navigation.xml
app/src/main/res/layout/item_comment.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_comments.xml
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/test/TestItem.java
app/src/test/java/io/github/hidroh/materialistic/widget/NavFloatingActionButtonTest.java

Add navigation FAB

---

app/src/main/java/io/github/hidroh/materialistic/Preferences.java

Fix default preference values

---

app/src/main/java/io/github/hidroh/materialistic/AdBlocker.java

Use Observable.fromCallable

---

app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/ThreadPreviewActivity.java
app/src/main/java/io/github/hidroh/materialistic/UserActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java

Seem to be causing inconsistent layout and/or same stable IDs exceptions

Remove RecyclerView optimization

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/ListFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsItem.java
app/src/main/java/io/github/hidroh/materialistic/widget/SinglePageItemRecyclerViewAdapter.java

Reduce saved bundle size

---

app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/BaseWebFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/PopupSettingsFragment.java
app/src/main/java/io/github/hidroh/materialistic/SettingsActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/NavFloatingActionButton.java
app/src/main/res/drawable/ic_list_white_24dp.xml
app/src/main/res/drawable/ic_local_library_white_24dp.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/help_navigation.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_category.xml
app/src/main/res/xml/preferences_comments.xml
app/src/main/res/xml/preferences_display.xml
app/src/main/res/xml/preferences_font.xml
app/src/main/res/xml/preferences_list.xml
app/src/main/res/xml/preferences_widget.xml
app/src/test/java/io/github/hidroh/materialistic/SettingsActivityTest.java

Duplicate preferences to settings screen

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/BaseWebFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/LazyLoadFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/HackerNewsClient.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java
app/src/main/res/layout/toolbar_web.xml
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentLazyLoadTest.java
app/src/test/java/io/github/hidroh/materialistic/test/WebActivity.java

Lazy loading to rely on tab change events

---

app/src/main/res/layout/fragment_web.xml

Allow text input focus in WebView

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java

'Open in browser' for HN links fixed

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_list.xml
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java

Add toggle option for swipe gestures

---

app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java

Re-set preferences on create/recreate

---

app/src/main/java/io/github/hidroh/materialistic/BaseWebFragment.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/LazyLoadFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java

Retain WebView during orientation change

---

app/src/main/java/io/github/hidroh/materialistic/BaseWebFragment.java

Retain scroll position when toggling fullscreen

---

app/src/main/res/layout/fragment_item.xml

Allow pull to refresh empty comments

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/DrawerActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/NavFloatingActionButton.java
app/src/main/res/drawable/ic_dummy_transparent_24dp.xml
app/src/main/res/layout/drawer.xml

Reposition drawer toggle, persist fab nav position

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java
app/src/main/res/values/strings.xml

Display full text for comment items

---

app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/NavFloatingActionButton.java
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_comments.xml

Make vibration optional

---

app/src/main/java/io/github/hidroh/materialistic/LazyLoadFragment.java
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/ReadabilityFragmentLazyLoadTest.java

Relax lazy loading for non-wifi connections

---

app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/PeekabooTouchHelperCallback.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/res/menu/menu_contextual_story.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_list.xml
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java

Allow single story refresh

---

app/src/main/java/io/github/hidroh/materialistic/BaseListActivity.java
app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java
app/src/main/res/layout/item_header.xml
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java

Default open comments should always open comments

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java

Hide empty state upon refreshed

---

app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java

Respect default tab preference

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/LazyLoadFragment.java
app/src/main/java/io/github/hidroh/materialistic/WebFragment.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemPagerAdapter.java

Retain item comments across orientation change

---

README.md
app/build.gradle
app/src/main/java/io/github/hidroh/materialistic/data/ReadabilityClient.java
app/src/main/res/values/license.xml
app/src/test/java/io/github/hidroh/materialistic/data/ReadabilityClientTest.java
app/src/test/java/io/github/hidroh/materialistic/data/TestRestServiceFactory.java

Replace Readability API with Mercury API

---

app/src/main/java/io/github/hidroh/materialistic/LoginActivity.java

Trim input username and password

---

app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetHelper.java

Fix broadcast override

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/file_paths.xml
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/data/FavoriteManagerTest.java

Share exported saved stories as file

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ItemRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/ItemFragmentSinglePageTest.java
app/src/test/java/io/github/hidroh/materialistic/ListFragmentViewHolderTest.java
app/src/test/java/io/github/hidroh/materialistic/TestApplication.java

Replace share intent chooser with implicit intent

---

app/src/main/java/io/github/hidroh/materialistic/widget/CacheableWebView.java
app/src/main/java/io/github/hidroh/materialistic/widget/WebView.java
app/src/test/java/io/github/hidroh/materialistic/BaseListActivityLandTest.java

Avoid overriding placeholder URLs

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetHelper.java
app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetRefreshJobService.java
app/src/test/java/io/github/hidroh/materialistic/appwidget/WidgetConfigActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/appwidget/WidgetProviderTest.java

Use JobScheduler to periodically update widget on API 21+

---

app/src/main/java/io/github/hidroh/materialistic/BaseListFragment.java
app/src/main/java/io/github/hidroh/materialistic/FavoriteFragment.java
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java

Render after data restoration

---

app/src/main/java/io/github/hidroh/materialistic/AlertDialogBuilder.java
app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/res/values/strings.xml
app/src/test/java/io/github/hidroh/materialistic/DrawerActivityLoginTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java

Remove account from account chooser popup

---

app/src/main/java/io/github/hidroh/materialistic/LoginActivity.java
app/src/main/java/io/github/hidroh/materialistic/accounts/UserServicesClient.java
app/src/main/res/layout/activity_login.xml
app/src/test/java/io/github/hidroh/materialistic/accounts/UserServicesClientTest.java

Show meaningful error messages for login

---

.travis.yml
build.gradle

Drop sdk manager on the floor

---

app/src/main/java/io/github/hidroh/materialistic/DataModule.java
app/src/main/java/io/github/hidroh/materialistic/data/FavoriteManager.java
app/src/main/java/io/github/hidroh/materialistic/data/SyncDelegate.java
app/src/main/java/io/github/hidroh/materialistic/data/SyncScheduler.java
app/src/main/java/io/github/hidroh/materialistic/widget/FavoriteRecyclerViewAdapter.java
app/src/main/java/io/github/hidroh/materialistic/widget/ListRecyclerViewAdapter.java
app/src/main/res/drawable/ic_bookmark_border_white_24dp.xml
app/src/main/res/drawable/ic_bookmark_white_24dp.xml
app/src/main/res/menu/menu_favorite_action.xml
app/src/main/res/values/ids.xml
app/src/test/java/io/github/hidroh/materialistic/FavoriteActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/TestActivityModule.java
app/src/test/java/io/github/hidroh/materialistic/data/ItemSyncAdapterTest.java
app/src/test/java/io/github/hidroh/materialistic/data/ItemSyncJobServiceTest.java

Allow refreshing saved stories

---

app/src/main/java/io/github/hidroh/materialistic/widget/NavFloatingActionButton.java

Fix incorrect vibration preference key

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/FabAwareScrollBehavior.java
app/src/main/res/layout-w820dp-land/activity_list.xml
app/src/main/res/layout/activity_item.xml
app/src/main/res/values/non_translatable.xml

https://issuetracker.google.com/issues/37130108

Scrolling view should trigger FAB visibility

---

app/src/main/java/io/github/hidroh/materialistic/ItemActivity.java

Always use in-app browser for stories with body

---

app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetConfigActivity.java
app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetHelper.java
app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetService.java
app/src/test/java/io/github/hidroh/materialistic/appwidget/WidgetConfigActivityTest.java
app/src/test/java/io/github/hidroh/materialistic/appwidget/WidgetServiceTest.java

This reverts commit 7f6ee17588fa029094ee23f39f6f2e79566203a2.

Revert "Pass along widget config for widgets"

---

app/src/main/java/io/github/hidroh/materialistic/Application.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/ThemedActivity.java
app/src/main/java/io/github/hidroh/materialistic/preference/ThemePreference.java
app/src/main/res/values-night-v23/themes.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/preferences_display.xml
app/src/test/java/io/github/hidroh/materialistic/PreferencesThemeTest.java
app/src/test/java/io/github/hidroh/materialistic/preference/ThemePreferenceTest.java

Support auto day-night themes

---

app/src/main/java/io/github/hidroh/materialistic/ItemFragment.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/SinglePageItemRecyclerViewAdapter.java
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_comments.xml

Add option to adjust color code opacity

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/test/java/io/github/hidroh/materialistic/AppUtilsTest.java

Opening comment URLs to follow custom tabs setting

---

app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/java/io/github/hidroh/materialistic/widget/StoryRecyclerViewAdapter.java
app/src/main/res/values/arrays.xml

Add share to swipe options

---

app/src/main/java/io/github/hidroh/materialistic/data/FileDownloader.java

Serve PDF file from cache if exists

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/CustomTabsDelegate.java
app/src/main/java/io/github/hidroh/materialistic/Preferences.java
app/src/main/res/values/strings.xml

Custom tabs API is now open for other browsers and not just Chrome
anymore, so we should not favor Chrome over default browser.

Support custom tabs from default browser

---

app/src/main/java/io/github/hidroh/materialistic/appwidget/WidgetHelper.java

Broadcast explicit intent

---

app/src/main/java/io/github/hidroh/materialistic/NetworkModule.java

https://github.com/square/okhttp/issues/3537

Disable StrictMode error

---

app/src/main/java/io/github/hidroh/materialistic/data/MaterialisticDatabase.java
app/src/main/java/io/github/hidroh/materialistic/data/android/Cache.java

LiveData.postValue() is optimized to take the last value, probably
shouldn't use LiveData for event anyway.

Fix viewed not set

---

app/src/main/res/layout/appwidget.xml
app/src/main/res/layout/appwidget_dark.xml
app/src/main/res/layout/appwidget_light.xml

Fixes #1212 
Fixes #1217 
Fixes #1219 
Fixes #1223 
Fixes #1227 
Fixes #1230
Fixes #1234

Fix broken Nova launcher widgets

---

app/src/main/java/io/github/hidroh/materialistic/AppUtils.java
app/src/main/java/io/github/hidroh/materialistic/widget/AdBlockWebViewClient.java
app/src/main/java/io/github/hidroh/materialistic/widget/WebView.java

Fix trailing / in URL, add missing WebViewClient override
